branches:
  except:
    - "unity-cloud-build"
    - gh-pages
    - mb-pages

image: Visual Studio 2015

init:
  - git config --global core.autocrlf input

#don't use 'shallow_clone: true' as we have submodules
clone_depth: 5

environment:
  GITHUB_TOKEN:
    secure: lJJOC3O25ATwK7jNt2TeYC9LexbMpef6ZSJDS8J4OFYABWt53IDe8BPcBNuELiyJ
  MAPBOX_ACCESS_TOKEN:
    secure: dMZloaDRX0kslhjJRbDySkawDtY+1/42ke/v1B2LEQjSnvSp4RWTEkrxuyca3B4Y+Tw4dGg5KI9mL2WFvMQyI49UuIRoVACbIyr6s5pvn4bme5fKhbs/XxpecpzYOVSt

build_script:
#let UnityPackager finish sucessfully, even after encounting errors, eg missing '.meta' files
  - SET UNITYPACKAGER_RAISE_ERROR_ON_FAILURE=0
  - SET PATH=%CD%\scriptcs;%PATH%
  - SET PATH=%CD%\docfx;%PATH%
  - SET PATH=C:\Program Files\7-Zip;%PATH%
#get scriptcs
  - powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/mapbox/mapbox-sdk-cs/master/scripts/get-scriptcs.ps1'))"
#build and publish documentation, create unitypackage
  - scriptcs scripts\build.csx

artifacts:
  - path: 'mapbox-unity-sdk_*.unitypackage'
    name: UnityPackage
  - path: documentation\docfx_project\_site
    name: site
